include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o
obj-y   +=  otm8019a_wvga_dsi_vdo_dijing.o
obj-y   +=  otm8018b_wvga_dsi_vdo_dijing.o
obj-y   +=  nt35512_wvga_dsi_vdo_txd.o
