/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6  for MT6582. Copyright MediaTek Inc. (C) 2013.
 * Thu Jul 23 17:01:25 2015
 * Do Not Modify the File.
 */



#include <linux/types.h>
#include <mach/mt_typedefs.h>
#include <mach/mt_pm_ldo.h>


void pmu_drv_tool_customization_init(void)
{
}




